### ISSUE TITLE
Add scripts to simplify deployment and usage

### ISSUE THREAD

**Issue by tobyash86** [tobyash86/WebGoat.NETCore#1]
Feedback from Dave W.:

> Whatever you can do to make it SUPER EASY to use, is always good. If you look at the root directory of my OWASP project: https://github.com/OWASP/Benchmark you'll see things like:
>
> - URL file that points to the web app home page
> - various prebuilt scripts to do common tasks

**Comment by pkruk2** [comment]
I've added pull request, although I'm not convinced of necessity of this change.
