### ISSUE TITLE
My Account link should redirect to account information

### ISSUE THREAD

**Issue by tobyash86** [tobyash86/WebGoat.NETCore#11]
Feedback from Dave W.:

> Going to 'My Account' takes you to the login page? I would have thought it would have shown info about 'My Account'.

**Comment by pkruk2** [comment]
I can't reproduce this. It takes me to MyAccount page with following links:

```

Activities

    My account information
    My orders
    Change my password

```

**Comment by tobyash86** [comment]
I can't do it as well. Closing for now, until we get new feedback from Dave.
Thanks!
